from datetime import datetime

import requests

url = 'https://www.google.com/search?q=sdf&sxsrf=APq-WBvlzIv4aLh7Jaub3BKDqA84mIaYMg%3A1647371828079&ei=NOYwYs2uBIyYrwTg1LzICw&ved=0ahUKEwjNmICl6sj2AhUMzIsKHWAqD7kQ4dUDCA4&uact=5&oq=sdf&gs_lcp=Cgdnd3Mtd2l6EAMyEAguELEDEMcBENEDENQCEEMyCgguELEDENQCEEMyBAgAEEMyCAgAEIAEELEDMgsILhCABBDHARCvATIFCAAQgAQyCAgAEIAEELEDMgUIABCABDIFCAAQgAQyBQgAELEDOgcIIxCwAxAnOgcIABBHELADOgcIABCwAxBDOgsIABCwAxAKEAEQQzoMCC4QyAMQsAMQQxgBOhAILhDIAxCwAxAKEAEQQxgBOhIILhDHARCjAhDIAxCwAxBDGAE6EgguEMcBENEDEMgDELADEEMYAToPCC4Q1AIQyAMQsAMQQxgBOgQIIxAnOgoILhDHARDRAxBDOgsIABCABBCxAxCLAzoRCC4QgAQQsQMQxwEQ0QMQiwM6FwguEIAEELEDEMcBENEDEIsDEKgDENIDSgQIQRgASgQIRhgBUJ8JWJwKYN8LaAJwAXgAgAGlAYgBtgKSAQMwLjKYAQCgAQHIARS4AQLAAQHaAQYIARABGAg&sclient=gws-wiz'
data = {'url': 'fdkgjlksjdg.com/fdskg;k', 'exp': 1}
resp = requests.get(f'http://127.0.0.1:5000/api/v1/get_short/?url={url}&exp=366')
print(resp.json())
